version: 2
jobs:
    build:
        working_directory: ~/app
        docker:
            - image: "circleci/node:12.18.4"
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - 'dependencies-cache-{{ checksum "package.json" }}'
                      - dependencies-cache
            - run:
                  name: Install dependencies and Serverless CLI
                  command: |
                      sudo npm i -g serverless
                      yarn
            - run:
                  name: Set AWS profile
                  command: |
                      serverless config credencials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
            - run:
                  name: Deploy application
                  command: serverless deploy -v
            - save_cache:
                  paths:
                      - node_modules
                  key: 'dependencies-cache-{{ checksum "package.json" }}'
workflows:
    version: 2
    deploy_dev:
        jobs:
            - build:
                  context: memes-dev
                  filters:
                      branches:
                          only:
                              - develop
    deploy_prod:
        jobs:
            - build:
                  context: memes-prod
                  filters:
                      branches:
                          only:
                              - master
