const event = {
    body: null,
    headers: {
        "Content-Type": "application/json",
        "User-Agent": "PostmanRuntime/7.26.5",
        Accept: "*/*",
        "Cache-Control": "no-cache",
        "Postman-Token": "10c475cf-6caf-4895-8b64-6dc183f896a3",
        Host: "localhost:4000",
        "Accept-Encoding": "gzip, deflate, br",
        Connection: "keep-alive",
        "Content-Length": "773",
    },
    httpMethod: "GET",
    isBase64Encoded: false,
    multiValueHeaders: {
        "Content-Type": ["application/json"],
        "User-Agent": ["PostmanRuntime/7.26.5"],
        Accept: ["*/*"],
        "Cache-Control": ["no-cache"],
        "Postman-Token": ["10c475cf-6caf-4895-8b64-6dc183f896a3"],
        Host: ["localhost:4000"],
        "Accept-Encoding": ["gzip, deflate, br"],
        Connection: ["keep-alive"],
        "Content-Length": ["773"],
    },
    multiValueQueryStringParameters: null,
    path: "/memes",
    pathParameters: null,
    queryStringParameters: null,
    requestContext: {
        accountId: "offlineContext_accountId",
        apiId: "offlineContext_apiId",
        authorizer: {
            principalId: "offlineContext_authorizer_principalId",
        },
        domainName: "offlineContext_domainName",
        domainPrefix: "offlineContext_domainPrefix",
        extendedRequestId: "ckfrzu0j300003kutb8eqfjbh",
        httpMethod: "GET",
        identity: {
            accessKey: null,
            accountId: "offlineContext_accountId",
            apiKey: "offlineContext_apiKey",
            caller: "offlineContext_caller",
            cognitoAuthenticationProvider:
                "offlineContext_cognitoAuthenticationProvider",
            cognitoAuthenticationType:
                "offlineContext_cognitoAuthenticationType",
            cognitoIdentityId: "offlineContext_cognitoIdentityId",
            cognitoIdentityPoolId: "offlineContext_cognitoIdentityPoolId",
            principalOrgId: null,
            sourceIp: "127.0.0.1",
            user: "offlineContext_user",
            userAgent: "PostmanRuntime/7.26.5",
            userArn: "offlineContext_userArn",
        },
        path: "/memes",
        protocol: "HTTP/1.1",
        requestId: "ckfrzu0j300013kut0fad8evq",
        requestTime: "02/Oct/2020:10:36:30 +0200",
        requestTimeEpoch: 1601627790632,
        resourceId: "offlineContext_resourceId",
        resourcePath: "/dev/memes",
        stage: "dev",
    },
    resource: "/dev/memes",
};
